
# ddcの依存
[[plugins]]
repo='vim-denops/denops.vim'

# ddc source
[[plugins]]
repo='matsui54/ddc-dictionary'
on_source='ddc.vim'
[[plugins]]
repo='Shougo/ddc-around'
on_source='ddc.vim'

# ddc filter
[[plugins]]
repo='Shougo/ddc-matcher_head'
on_source='ddc.vim'
[[plugins]]
repo='Shougo/ddc-sorter_rank'
on_source='ddc.vim'
[[plugins]]
repo='Shougo/ddc-filter-converter_remove_overlap'
on_source='ddc.vim'

# ddc UI
[[plugins]]
repo = 'Shougo/ddc-ui-native'
on_source = 'ddc.vim'



# 補完
[[plugins]]
repo='Shougo/ddc.vim'
depends='denops.vim'
on_event = 'InsertEnter'
hook_source='''
    " uiの設定
    call ddc#custom#patch_global('ui', 'native')

    " Use matcher_head and sorter_rank.
    " https://github.com/Shougo/ddc-matcher_head
    " https://github.com/Shougo/ddc-sorter_rank
    call ddc#custom#patch_global('sourceOptions', {
          \ '_': {
          \   'matchers': ['matcher_head'],
          \   'sorters': ['sorter_rank']},
          \ })

    " Customize global setting
    " Use around source.
    " https://github.com/Shougo/ddc-around
    call ddc#custom#patch_global('sources', ['around'])

    " Change source options
    call ddc#custom#patch_global('sourceOptions', {
          \ 'around': {'mark': 'A'},
          \ })
    call ddc#custom#patch_global('sourceParams', {
          \ 'around': {'maxSize': 500},
          \ })

    " Customize settings on a filetype
    call ddc#custom#patch_filetype(['c', 'cpp'], 'sources', ['around', 'clangd'])
    call ddc#custom#patch_filetype(['c', 'cpp'], 'sourceOptions', {
          \ 'clangd': {'mark': 'C'},
          \ })
    call ddc#custom#patch_filetype('markdown', 'sourceParams', {
          \ 'around': {'maxSize': 100},
          \ })

    " mugen独自の設定
    call ddc#custom#patch_filetype(['mugen'],'sources', ['dictionary'])

    call ddc#custom#patch_filetype(['mugen'],'sourceOptions', {
          \ '_': {'matchers': ['matcher_head']},
          \ 'dictionary': {'mark': 'D'},
          \ })

    call ddc#custom#patch_filetype(['mugen'],'sourceParams', {
            \ 'dictionary': {'dictPaths': 
            \ [
            \ $VIM_CONFIG_DIR .. '\dict\mugen_trigger.dict',
            \ $VIM_CONFIG_DIR .. '\dict\mugen_statectrler.dict',
            \ $VIM_CONFIG_DIR .. '\dict\mugen_param.dict',
            \ $VIM_CONFIG_DIR .. '\dict\mugen_mytrig.dict',
            \ $VIM_CONFIG_DIR .. '\dict\mugen_redirect.dict',
            \ ],
            \ 'smartCase': v:true,
            \ 'showMenu': v:false,
            \ }
            \})


    " <TAB>: completion. ddc.vim
    inoremap <silent><expr> <TAB>
     \ pumvisible() ? '<C-n>' :
     \ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s'<Bar><Bar> getline('.')[col('.') - 2] =~# ';') ?
     \ '<TAB>' : ddc#map#manual_complete()

    " <S-TAB>: completion back. ddc.vim
    inoremap <expr><S-TAB>  pumvisible() ? '<C-p>' : '<C-h>'

    " 補完の動作をいい感じに
    inoremap <expr><CR>  pumvisible() ? '<C-y>' : '<CR>'

    " Use ddc.
    call ddc#enable()

'''


