# ===========================================
# Lazy load plugins
# ===========================================


# カッコとかを閉じる
[[plugins]]
repo='cohama/lexima.vim'
on_event = ['InsertEnter']
hook_add='''
    let g:lexima_no_default_rules=1
'''

# スニペット
[[plugins]]
repo='Shougo/neosnippet.vim'
on_event = ['InsertEnter']
hook_source='''
    " Plugin key-mappings. neosnippet.vim
    " Note: It must be "imap" and "smap".  It uses <Plug> mappings.
    inoremap <C-k>     <Plug>(neosnippet_expand_or_jump)
    snoremap <C-k>     <Plug>(neosnippet_expand_or_jump)
    xnoremap <C-k>     <Plug>(neosnippet_expand_target)

    " SuperTab like snippets behavior. neosnippet.vim
    " Note: It must be "imap" and "smap".  It uses <Plug> mappings.
    snoremap <expr><TAB> neosnippet#expandable_or_jumpable() ?
    \ '\<Plug>(neosnippet_expand_or_jump)' : '\<TAB>'

    " For conceal markers.
    if has('conceal')
      set conceallevel=2 concealcursor=niv
    endif
'''

[[plugins]]
repo='Shougo/neosnippet-snippets'
on_source='neosnippet.vim'
hook_source='''
    " Enable snipMate compatibility feature.
    let g:neosnippet#enable_snipmate_compatibility = 1
    " Tell Neosnippet about the other snippets
    let g:neosnippet#snippets_directory=$VIM_CONFIG_DIR .. '/snippets'
'''
