# ===========================================
# ddu.vim toml (ff)
# ===========================================

# ファジーファインダー
[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'
# 再帰的なファイル
[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'
# 部分文字列一致
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'
# ファイル操作
[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'
# ファイルアイコン
[[plugins]]
repo='ryota2357/ddu-column-icon_filename'
on_source = 'ddu.vim'

# ddu(for fuzzy finder)
[[plugins]]
repo='Shougo/ddu.vim'
depends='denops.vim'
on_event = ['VimEnter']
hook_source='''
    call ddu#custom#alias('column', 'icon_filename_for_ff', 'icon_filename')
    call ddu#custom#patch_global({
    \   'ui': 'ff',
    \   'sources': [
    \     {
    \       'name': 'file_rec',
    \       'params': {
    \         'ignoredDirectories': ['.git', 'node_modules', 'vendor', '.next', '.vscode']
    \       }
    \     }
    \   ],
    \   'columns': [
    \       'icon_filename'
    \   ],
    \   'sourceOptions': {
    \     '_': {
    \       'matchers': ['matcher_substring'],
    \       'columns': ['icon_filename_for_ff'],
    \     },
    \   },
    \   'filterParams': {
    \     'matcher_substring': {
    \       'highlightMatched': 'Title',
    \     },
    \   },
    \   'kindOptions': {
    \     'file': {
    \       'defaultAction': 'open',
    \     },
    \   },
    \   'uiParams': {
    \     'ff': {
    \       'startFilter': v:false,
    \       'prompt': '> ',
    \     }
    \   },
    \   'columnParams': {
    \     'icon_filename_for_ff': {
    \       'defaultIcon': {'icon':''},
    \       'padding': 0,
    \       'pathDisplayOption': 'relative',
    \     }
    \   },
    \ })


    autocmd FileType ddu-ff call s:ddu_my_settings()
    function! s:ddu_my_settings() abort
        nnoremap <buffer><silent> <CR>
        \ <Cmd>call ddu#ui#ff#do_action('itemAction', {'name': 'open', 'params': {'command': 'vsplit'}})<CR>

        nnoremap <buffer><silent> c <Cmd>call ddu#ui#ff#do_action('itemAction',{'name': 'cd'})<CR>

        nnoremap <buffer> <Space> <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
        nnoremap <buffer> <C-r> <Cmd>call ddu#ui#ff#do_action('refreshItems')<CR>

        nnoremap <buffer><silent> i <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>

        nnoremap <buffer><silent> p <Cmd>call ddu#ui#ff#do_action('preview')<CR>

        nnoremap <buffer><silent> <Esc> <Cmd>call ddu#ui#ff#do_action('quit')<CR>
        nnoremap <buffer><silent> q <Cmd>call ddu#ui#ff#do_action('quit')<CR>

    endfunction

    autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()
    function! s:ddu_filter_my_settings() abort
      inoremap <buffer><silent> <CR>
        \ <Esc><Cmd>close<CR>

      inoremap <buffer><silent> <Esc>
        \ <Esc><Cmd>close<CR>

      nnoremap <buffer><silent> <CR>
        \ <Cmd>close<CR>

      nnoremap <buffer><silent> <Esc>
        \ <Cmd>close<CR>

      inoremap <buffer><silent> jj
        \ <Cmd>close<CR>
      nnoremap <buffer><silent> jj
        \ <Cmd>close<CR>
    endfunction

    nnoremap <silent> <Leader>f <Cmd>call ddu#start({})<CR>
'''
