

# スニペット
[[plugins]]
repo='Shougo/neosnippet.vim'
hook_add='''
    " Plugin key-mappings. neosnippet.vim
    " Note: It must be "imap" and "smap".  It uses <Plug> mappings.
    imap <C-k>     <Plug>(neosnippet_expand_or_jump)
    smap <C-k>     <Plug>(neosnippet_expand_or_jump)
    xmap <C-k>     <Plug>(neosnippet_expand_target)

    " SuperTab like snippets behavior. neosnippet.vim
    " Note: It must be "imap" and "smap".  It uses <Plug> mappings.
    "imap <expr><TAB>
    " \ ddc#map#pum_visible() ? '\<C-n>' :
    " \ neosnippet#expandable_or_jumpable() ?
    " \    '\<Plug>(neosnippet_expand_or_jump)' : '\<TAB>'
    smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
    \ '\<Plug>(neosnippet_expand_or_jump)' : '\<TAB>'

    " For conceal markers.
    if has('conceal')
      set conceallevel=2 concealcursor=niv
    endif
'''

[[plugins]]
repo='Shougo/neosnippet-snippets'
hook_add='''
    " Enable snipMate compatibility feature.
    let g:neosnippet#enable_snipmate_compatibility = 1
    " Tell Neosnippet about the other snippets
    let g:neosnippet#snippets_directory=$VIM .. '\snippets'
'''



# 括弧の色付け 
[[plugins]] 
repo='luochen1990/rainbow' 
hook_add=''' 
    let g:rainbow_conf = {
    \	'separately': {
    \		'*': {},
    \		'mugen': {
    \			'parentheses': ['start=/(/ end=/)/ fold'], 
    \		},
    \	}
    \}
''' 
