# ===========================================
# Lazy load plugins
# ===========================================


# カッコとかを閉じる
[[plugins]]
repo='cohama/lexima.vim'
on_event = ['InsertEnter']
hook_add='''
    let g:lexima_no_default_rules=1
'''

